# longhorn-product-images-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-images-pvc
spec:
  accessModes:
    - ReadWriteMany  # Longhorn hỗ trợ RWX từ phiên bản 1.2.0+
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn