apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-product-secret
  namespace: ecommerce
type: Opaque
stringData:
  PRODUCT_DB_PASSWORD: password
  PRODUCT_DB_HOST: "postgres-products"
  PRODUCT_DB_PORT: "5432"
  PRODUCT_DB_USER: "postgres-products"
  PRODUCT_DB_NAME: "products"
  PRODUCT_DB_SSLMODE: "disable"
  MIGRATION_PATH: "file:///app/migrations"
  AUTO_MIGRATE: "false"
  MINIO_ACCESS_KEY_ID: your_access_key_id
  MINIO_SECRET_ACCESS_KEY: your_secret_access_key
  STORAGE_PROVIDER: minio
  MINIO_ENDPOINT: minioapi.deploy.io.vn
  MINIO_USE_SSL: true
  MINIO_BUCKET_NAME: images
  MINIO_BASE_URL: https://minioapi.deploy.io.vn
  MINIO_PRESIGNED_TTL: 3600
  MINIO_LOCATION: us-east-1
