apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-product-secret
  namespace: ecommerce
type: Opaque
stringData:
  PRODUCT_DB_PASSWORD: password
  PRODUCT_DB_HOST: "postgres-products"
  PRODUCT_DB_PORT: "5432"
  PRODUCT_DB_USER: "postgres-products"
  PRODUCT_DB_NAME: "products"
  PRODUCT_DB_SSLMODE: "disable"
  MIGRATION_PATH: "file:///app/migrations"
  AUTO_MIGRATE: "false"
