services:
  broker-service:
    container_name: broker-service
    image: broker-service:v1
    build:
      context: ./services/broker-service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - net
  authentication-service:
    container_name: authentication-service
    image: authenticate-service:v1
    build:
      context: ./services/authentication-service
    restart: always
    ports:
      - "9000:9000"
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
    networks:
      - net

  product-service:
    container_name: product-service
    image: product-service:v1
    build:
      context: ./services/product-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      DSN: "host=postgres-products port=5432 user=postgres-products password=password dbname=products sslmode=disable timezone=UTC connect_timeout=5"
    depends_on:
      - postgres-products
    networks:
      - net

  logger-service:
    container_name: logger-service
    image: logger-service:v1
    build:
      context: ./services/logger-service
    restart: always
    networks:
      - net

  mail-service:
    container_name: mail-service
    image: mail-service:v1
    build:
      context: ./services/mail-service
    restart: always
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "Livius Vuong"
      FROM_ADDR: livius.vuong@example.com
    networks:
      - net

  listener-service:
    container_name: listener-service
    image: listener-service:v1
    build:
      context: ./services/listener-service
    restart: always
    networks:
      - net

  postgres:
    container_name: postgres
    image: "postgres:14.0"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      POSTGRES_MULTIPLE_DATABASES: users,products
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data/
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - net

  postgres-products:
    container_name: postgres-products
    image: "postgres:14.0"
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres-products
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    volumes:
      - ./db-data/postgres-products:/var/lib/postgresql/data/
      - ./postgres-init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: bash -c "chmod +x /docker-entrypoint-initdb.d/init-db.sql && docker-entrypoint.sh postgres"
    networks:
      - net

  mongodb:
    image: "mongo:4.2.16-bionic"
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
    networks:
      - net

  # Testing SMTP Server
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - net

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.9-alpine"
    ports:
      - "5672:5672"
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/
    networks:
      - net

networks:
  net:
    driver: bridge
