apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-users-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage-retain
  resources:
    requests:
      storage: 5Gi
