apiVersion: v1
kind: Service
metadata:
  name: ecommerce-auth-service
  namespace: ecommerce
spec:
  selector:
    app: ecommerce-auth-app
  ports:
    - name: tcp-grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP 