// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "authentication-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is a mock of UserRepository interface
type MockUserRepository struct {
	mock.Mock
}

// CreateUser mocks base method
func (m *MockUserRepository) CreateUser(ctx context.Context, user *domain.User) error {
	args := m.Called(ctx, user)
	return args.Error(0)
}

// GetUserByID mocks base method
func (m *MockUserRepository) GetUserByID(ctx context.Context, id string) (*domain.User, error) {
	args := m.Called(ctx, id)
	
	var user *domain.User
	if args.Get(0) != nil {
		user = args.Get(0).(*domain.User)
	}
	
	return user, args.Error(1)
}

// GetUserByEmail mocks base method
func (m *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	args := m.Called(ctx, email)
	
	var user *domain.User
	if args.Get(0) != nil {
		user = args.Get(0).(*domain.User)
	}
	
	return user, args.Error(1)
}

// UpdateUser mocks base method
func (m *MockUserRepository) UpdateUser(ctx context.Context, user *domain.User) error {
	args := m.Called(ctx, user)
	return args.Error(0)
}

// UpdateRefreshToken mocks base method
func (m *MockUserRepository) UpdateRefreshToken(ctx context.Context, userID, refreshToken string) error {
	args := m.Called(ctx, userID, refreshToken)
	return args.Error(0)
}

// LogoutFromAllDevices mocks base method
func (m *MockUserRepository) LogoutFromAllDevices(ctx context.Context, userID string) error {
	args := m.Called(ctx, userID)
	return args.Error(0)
}

// UserExists mocks base method
func (m *MockUserRepository) UserExists(ctx context.Context, email string) (bool, error) {
	args := m.Called(ctx, email)
	return args.Bool(0), args.Error(1)
} 