// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: proto/product/product.proto

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	// Product operations
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error)
	GetProductBySlug(ctx context.Context, in *GetProductBySlugRequest, opts ...grpc.CallOption) (*Product, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	CreateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*CreateProductResponse, error)
	UpdateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*StatusResponse, error)
	PatchProduct(ctx context.Context, in *PatchProductRequest, opts ...grpc.CallOption) (*Product, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Review operations
	GetProductReviews(ctx context.Context, in *GetProductReviewsRequest, opts ...grpc.CallOption) (*GetProductReviewsResponse, error)
	AddProductReview(ctx context.Context, in *ProductReview, opts ...grpc.CallOption) (*AddProductReviewResponse, error)
	UpdateProductReview(ctx context.Context, in *ProductReview, opts ...grpc.CallOption) (*StatusResponse, error)
	// Image operations
	GetProductImages(ctx context.Context, in *GetProductImagesRequest, opts ...grpc.CallOption) (*GetProductImagesResponse, error)
	UploadProductImage(ctx context.Context, in *UploadProductImageRequest, opts ...grpc.CallOption) (*UploadProductImageResponse, error)
	DeleteProductImage(ctx context.Context, in *DeleteProductImageRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	SetPrimaryProductImage(ctx context.Context, in *SetPrimaryProductImageRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// New method for retrieving image file data
	GetProductImageFile(ctx context.Context, in *GetProductImageFileRequest, opts ...grpc.CallOption) (*GetProductImageFileResponse, error)
	// New method for generating presigned URLs
	GetPresignedURL(ctx context.Context, in *PresignedURLRequest, opts ...grpc.CallOption) (*PresignedURLResponse, error)
	// Testimonials
	GetTopRatedTestimonials(ctx context.Context, in *GetTopRatedTestimonialsRequest, opts ...grpc.CallOption) (*GetTopRatedTestimonialsResponse, error)
	// Health check
	GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductBySlug(ctx context.Context, in *GetProductBySlugRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProductBySlug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/ListProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) CreateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	out := new(CreateProductResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) PatchProduct(ctx context.Context, in *PatchProductRequest, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/product.ProductService/PatchProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductReviews(ctx context.Context, in *GetProductReviewsRequest, opts ...grpc.CallOption) (*GetProductReviewsResponse, error) {
	out := new(GetProductReviewsResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProductReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) AddProductReview(ctx context.Context, in *ProductReview, opts ...grpc.CallOption) (*AddProductReviewResponse, error) {
	out := new(AddProductReviewResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/AddProductReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProductReview(ctx context.Context, in *ProductReview, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/UpdateProductReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductImages(ctx context.Context, in *GetProductImagesRequest, opts ...grpc.CallOption) (*GetProductImagesResponse, error) {
	out := new(GetProductImagesResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProductImages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UploadProductImage(ctx context.Context, in *UploadProductImageRequest, opts ...grpc.CallOption) (*UploadProductImageResponse, error) {
	out := new(UploadProductImageResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/UploadProductImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeleteProductImage(ctx context.Context, in *DeleteProductImageRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/DeleteProductImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SetPrimaryProductImage(ctx context.Context, in *SetPrimaryProductImageRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/SetPrimaryProductImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProductImageFile(ctx context.Context, in *GetProductImageFileRequest, opts ...grpc.CallOption) (*GetProductImageFileResponse, error) {
	out := new(GetProductImageFileResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProductImageFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetPresignedURL(ctx context.Context, in *PresignedURLRequest, opts ...grpc.CallOption) (*PresignedURLResponse, error) {
	out := new(PresignedURLResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetPresignedURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetTopRatedTestimonials(ctx context.Context, in *GetTopRatedTestimonialsRequest, opts ...grpc.CallOption) (*GetTopRatedTestimonialsResponse, error) {
	out := new(GetTopRatedTestimonialsResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetTopRatedTestimonials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility
type ProductServiceServer interface {
	// Product operations
	GetProduct(context.Context, *GetProductRequest) (*Product, error)
	GetProductBySlug(context.Context, *GetProductBySlugRequest) (*Product, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	CreateProduct(context.Context, *Product) (*CreateProductResponse, error)
	UpdateProduct(context.Context, *Product) (*StatusResponse, error)
	PatchProduct(context.Context, *PatchProductRequest) (*Product, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*StatusResponse, error)
	// Review operations
	GetProductReviews(context.Context, *GetProductReviewsRequest) (*GetProductReviewsResponse, error)
	AddProductReview(context.Context, *ProductReview) (*AddProductReviewResponse, error)
	UpdateProductReview(context.Context, *ProductReview) (*StatusResponse, error)
	// Image operations
	GetProductImages(context.Context, *GetProductImagesRequest) (*GetProductImagesResponse, error)
	UploadProductImage(context.Context, *UploadProductImageRequest) (*UploadProductImageResponse, error)
	DeleteProductImage(context.Context, *DeleteProductImageRequest) (*StatusResponse, error)
	SetPrimaryProductImage(context.Context, *SetPrimaryProductImageRequest) (*StatusResponse, error)
	// New method for retrieving image file data
	GetProductImageFile(context.Context, *GetProductImageFileRequest) (*GetProductImageFileResponse, error)
	// New method for generating presigned URLs
	GetPresignedURL(context.Context, *PresignedURLRequest) (*PresignedURLResponse, error)
	// Testimonials
	GetTopRatedTestimonials(context.Context, *GetTopRatedTestimonialsRequest) (*GetTopRatedTestimonialsResponse, error)
	// Health check
	GetHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (UnimplementedProductServiceServer) GetProduct(context.Context, *GetProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductServiceServer) GetProductBySlug(context.Context, *GetProductBySlugRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductBySlug not implemented")
}
func (UnimplementedProductServiceServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedProductServiceServer) CreateProduct(context.Context, *Product) (*CreateProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedProductServiceServer) UpdateProduct(context.Context, *Product) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedProductServiceServer) PatchProduct(context.Context, *PatchProductRequest) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchProduct not implemented")
}
func (UnimplementedProductServiceServer) DeleteProduct(context.Context, *DeleteProductRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedProductServiceServer) GetProductReviews(context.Context, *GetProductReviewsRequest) (*GetProductReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductReviews not implemented")
}
func (UnimplementedProductServiceServer) AddProductReview(context.Context, *ProductReview) (*AddProductReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProductReview not implemented")
}
func (UnimplementedProductServiceServer) UpdateProductReview(context.Context, *ProductReview) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductReview not implemented")
}
func (UnimplementedProductServiceServer) GetProductImages(context.Context, *GetProductImagesRequest) (*GetProductImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductImages not implemented")
}
func (UnimplementedProductServiceServer) UploadProductImage(context.Context, *UploadProductImageRequest) (*UploadProductImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadProductImage not implemented")
}
func (UnimplementedProductServiceServer) DeleteProductImage(context.Context, *DeleteProductImageRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductImage not implemented")
}
func (UnimplementedProductServiceServer) SetPrimaryProductImage(context.Context, *SetPrimaryProductImageRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPrimaryProductImage not implemented")
}
func (UnimplementedProductServiceServer) GetProductImageFile(context.Context, *GetProductImageFileRequest) (*GetProductImageFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductImageFile not implemented")
}
func (UnimplementedProductServiceServer) GetPresignedURL(context.Context, *PresignedURLRequest) (*PresignedURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPresignedURL not implemented")
}
func (UnimplementedProductServiceServer) GetTopRatedTestimonials(context.Context, *GetTopRatedTestimonialsRequest) (*GetTopRatedTestimonialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopRatedTestimonials not implemented")
}
func (UnimplementedProductServiceServer) GetHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProductBySlug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductBySlug(ctx, req.(*GetProductBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).CreateProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_PatchProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).PatchProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/PatchProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).PatchProduct(ctx, req.(*PatchProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProductReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductReviews(ctx, req.(*GetProductReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_AddProductReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductReview)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).AddProductReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/AddProductReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).AddProductReview(ctx, req.(*ProductReview))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProductReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductReview)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProductReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UpdateProductReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProductReview(ctx, req.(*ProductReview))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProductImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductImages(ctx, req.(*GetProductImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UploadProductImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadProductImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UploadProductImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/UploadProductImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UploadProductImage(ctx, req.(*UploadProductImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeleteProductImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeleteProductImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/DeleteProductImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeleteProductImage(ctx, req.(*DeleteProductImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SetPrimaryProductImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPrimaryProductImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SetPrimaryProductImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/SetPrimaryProductImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SetPrimaryProductImage(ctx, req.(*SetPrimaryProductImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProductImageFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductImageFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProductImageFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProductImageFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProductImageFile(ctx, req.(*GetProductImageFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetPresignedURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PresignedURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetPresignedURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetPresignedURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetPresignedURL(ctx, req.(*PresignedURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetTopRatedTestimonials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopRatedTestimonialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetTopRatedTestimonials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetTopRatedTestimonials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetTopRatedTestimonials(ctx, req.(*GetTopRatedTestimonialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "GetProductBySlug",
			Handler:    _ProductService_GetProductBySlug_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _ProductService_ListProducts_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _ProductService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ProductService_UpdateProduct_Handler,
		},
		{
			MethodName: "PatchProduct",
			Handler:    _ProductService_PatchProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ProductService_DeleteProduct_Handler,
		},
		{
			MethodName: "GetProductReviews",
			Handler:    _ProductService_GetProductReviews_Handler,
		},
		{
			MethodName: "AddProductReview",
			Handler:    _ProductService_AddProductReview_Handler,
		},
		{
			MethodName: "UpdateProductReview",
			Handler:    _ProductService_UpdateProductReview_Handler,
		},
		{
			MethodName: "GetProductImages",
			Handler:    _ProductService_GetProductImages_Handler,
		},
		{
			MethodName: "UploadProductImage",
			Handler:    _ProductService_UploadProductImage_Handler,
		},
		{
			MethodName: "DeleteProductImage",
			Handler:    _ProductService_DeleteProductImage_Handler,
		},
		{
			MethodName: "SetPrimaryProductImage",
			Handler:    _ProductService_SetPrimaryProductImage_Handler,
		},
		{
			MethodName: "GetProductImageFile",
			Handler:    _ProductService_GetProductImageFile_Handler,
		},
		{
			MethodName: "GetPresignedURL",
			Handler:    _ProductService_GetPresignedURL_Handler,
		},
		{
			MethodName: "GetTopRatedTestimonials",
			Handler:    _ProductService_GetTopRatedTestimonials_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _ProductService_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product/product.proto",
}

// CategoryServiceClient is the client API for CategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryServiceClient interface {
	GetCategoryByID(ctx context.Context, in *GetCategoryByIDRequest, opts ...grpc.CallOption) (*Category, error)
	GetCategoryBySlug(ctx context.Context, in *GetCategoryBySlugRequest, opts ...grpc.CallOption) (*Category, error)
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	CreateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	UpdateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*StatusResponse, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	SyncProductCounts(ctx context.Context, in *SyncProductCountsRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type categoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryServiceClient(cc grpc.ClientConnInterface) CategoryServiceClient {
	return &categoryServiceClient{cc}
}

func (c *categoryServiceClient) GetCategoryByID(ctx context.Context, in *GetCategoryByIDRequest, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/product.CategoryService/GetCategoryByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) GetCategoryBySlug(ctx context.Context, in *GetCategoryBySlugRequest, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/product.CategoryService/GetCategoryBySlug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, "/product.CategoryService/ListCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) CreateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, "/product.CategoryService/CreateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) UpdateCategory(ctx context.Context, in *Category, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.CategoryService/UpdateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.CategoryService/DeleteCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryServiceClient) SyncProductCounts(ctx context.Context, in *SyncProductCountsRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.CategoryService/SyncProductCounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServiceServer is the server API for CategoryService service.
// All implementations must embed UnimplementedCategoryServiceServer
// for forward compatibility
type CategoryServiceServer interface {
	GetCategoryByID(context.Context, *GetCategoryByIDRequest) (*Category, error)
	GetCategoryBySlug(context.Context, *GetCategoryBySlugRequest) (*Category, error)
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	CreateCategory(context.Context, *Category) (*CreateCategoryResponse, error)
	UpdateCategory(context.Context, *Category) (*StatusResponse, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*StatusResponse, error)
	SyncProductCounts(context.Context, *SyncProductCountsRequest) (*StatusResponse, error)
	mustEmbedUnimplementedCategoryServiceServer()
}

// UnimplementedCategoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCategoryServiceServer struct {
}

func (UnimplementedCategoryServiceServer) GetCategoryByID(context.Context, *GetCategoryByIDRequest) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryByID not implemented")
}
func (UnimplementedCategoryServiceServer) GetCategoryBySlug(context.Context, *GetCategoryBySlugRequest) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryBySlug not implemented")
}
func (UnimplementedCategoryServiceServer) ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedCategoryServiceServer) CreateCategory(context.Context, *Category) (*CreateCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedCategoryServiceServer) UpdateCategory(context.Context, *Category) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedCategoryServiceServer) DeleteCategory(context.Context, *DeleteCategoryRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedCategoryServiceServer) SyncProductCounts(context.Context, *SyncProductCountsRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncProductCounts not implemented")
}
func (UnimplementedCategoryServiceServer) mustEmbedUnimplementedCategoryServiceServer() {}

// UnsafeCategoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryServiceServer will
// result in compilation errors.
type UnsafeCategoryServiceServer interface {
	mustEmbedUnimplementedCategoryServiceServer()
}

func RegisterCategoryServiceServer(s grpc.ServiceRegistrar, srv CategoryServiceServer) {
	s.RegisterService(&CategoryService_ServiceDesc, srv)
}

func _CategoryService_GetCategoryByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).GetCategoryByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.CategoryService/GetCategoryByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).GetCategoryByID(ctx, req.(*GetCategoryByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_GetCategoryBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).GetCategoryBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.CategoryService/GetCategoryBySlug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).GetCategoryBySlug(ctx, req.(*GetCategoryBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.CategoryService/ListCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Category)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.CategoryService/CreateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).CreateCategory(ctx, req.(*Category))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Category)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.CategoryService/UpdateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).UpdateCategory(ctx, req.(*Category))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.CategoryService/DeleteCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryService_SyncProductCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncProductCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServiceServer).SyncProductCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.CategoryService/SyncProductCounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServiceServer).SyncProductCounts(ctx, req.(*SyncProductCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryService_ServiceDesc is the grpc.ServiceDesc for CategoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.CategoryService",
	HandlerType: (*CategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategoryByID",
			Handler:    _CategoryService_GetCategoryByID_Handler,
		},
		{
			MethodName: "GetCategoryBySlug",
			Handler:    _CategoryService_GetCategoryBySlug_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _CategoryService_ListCategories_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _CategoryService_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _CategoryService_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _CategoryService_DeleteCategory_Handler,
		},
		{
			MethodName: "SyncProductCounts",
			Handler:    _CategoryService_SyncProductCounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product/product.proto",
}

// BannerServiceClient is the client API for BannerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BannerServiceClient interface {
	GetBannerByID(ctx context.Context, in *GetBannerByIDRequest, opts ...grpc.CallOption) (*Banner, error)
	GetBannersByType(ctx context.Context, in *GetBannersByTypeRequest, opts ...grpc.CallOption) (*GetBannersByTypeResponse, error)
	ListBanners(ctx context.Context, in *ListBannersRequest, opts ...grpc.CallOption) (*ListBannersResponse, error)
	CreateBanner(ctx context.Context, in *Banner, opts ...grpc.CallOption) (*CreateBannerResponse, error)
	UpdateBanner(ctx context.Context, in *Banner, opts ...grpc.CallOption) (*StatusResponse, error)
	DeleteBanner(ctx context.Context, in *DeleteBannerRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type bannerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBannerServiceClient(cc grpc.ClientConnInterface) BannerServiceClient {
	return &bannerServiceClient{cc}
}

func (c *bannerServiceClient) GetBannerByID(ctx context.Context, in *GetBannerByIDRequest, opts ...grpc.CallOption) (*Banner, error) {
	out := new(Banner)
	err := c.cc.Invoke(ctx, "/product.BannerService/GetBannerByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) GetBannersByType(ctx context.Context, in *GetBannersByTypeRequest, opts ...grpc.CallOption) (*GetBannersByTypeResponse, error) {
	out := new(GetBannersByTypeResponse)
	err := c.cc.Invoke(ctx, "/product.BannerService/GetBannersByType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) ListBanners(ctx context.Context, in *ListBannersRequest, opts ...grpc.CallOption) (*ListBannersResponse, error) {
	out := new(ListBannersResponse)
	err := c.cc.Invoke(ctx, "/product.BannerService/ListBanners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) CreateBanner(ctx context.Context, in *Banner, opts ...grpc.CallOption) (*CreateBannerResponse, error) {
	out := new(CreateBannerResponse)
	err := c.cc.Invoke(ctx, "/product.BannerService/CreateBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) UpdateBanner(ctx context.Context, in *Banner, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.BannerService/UpdateBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) DeleteBanner(ctx context.Context, in *DeleteBannerRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.BannerService/DeleteBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BannerServiceServer is the server API for BannerService service.
// All implementations must embed UnimplementedBannerServiceServer
// for forward compatibility
type BannerServiceServer interface {
	GetBannerByID(context.Context, *GetBannerByIDRequest) (*Banner, error)
	GetBannersByType(context.Context, *GetBannersByTypeRequest) (*GetBannersByTypeResponse, error)
	ListBanners(context.Context, *ListBannersRequest) (*ListBannersResponse, error)
	CreateBanner(context.Context, *Banner) (*CreateBannerResponse, error)
	UpdateBanner(context.Context, *Banner) (*StatusResponse, error)
	DeleteBanner(context.Context, *DeleteBannerRequest) (*StatusResponse, error)
	mustEmbedUnimplementedBannerServiceServer()
}

// UnimplementedBannerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBannerServiceServer struct {
}

func (UnimplementedBannerServiceServer) GetBannerByID(context.Context, *GetBannerByIDRequest) (*Banner, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBannerByID not implemented")
}
func (UnimplementedBannerServiceServer) GetBannersByType(context.Context, *GetBannersByTypeRequest) (*GetBannersByTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBannersByType not implemented")
}
func (UnimplementedBannerServiceServer) ListBanners(context.Context, *ListBannersRequest) (*ListBannersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBanners not implemented")
}
func (UnimplementedBannerServiceServer) CreateBanner(context.Context, *Banner) (*CreateBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBanner not implemented")
}
func (UnimplementedBannerServiceServer) UpdateBanner(context.Context, *Banner) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBanner not implemented")
}
func (UnimplementedBannerServiceServer) DeleteBanner(context.Context, *DeleteBannerRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBanner not implemented")
}
func (UnimplementedBannerServiceServer) mustEmbedUnimplementedBannerServiceServer() {}

// UnsafeBannerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BannerServiceServer will
// result in compilation errors.
type UnsafeBannerServiceServer interface {
	mustEmbedUnimplementedBannerServiceServer()
}

func RegisterBannerServiceServer(s grpc.ServiceRegistrar, srv BannerServiceServer) {
	s.RegisterService(&BannerService_ServiceDesc, srv)
}

func _BannerService_GetBannerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).GetBannerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.BannerService/GetBannerByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).GetBannerByID(ctx, req.(*GetBannerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_GetBannersByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannersByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).GetBannersByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.BannerService/GetBannersByType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).GetBannersByType(ctx, req.(*GetBannersByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_ListBanners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBannersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).ListBanners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.BannerService/ListBanners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).ListBanners(ctx, req.(*ListBannersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_CreateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Banner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).CreateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.BannerService/CreateBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).CreateBanner(ctx, req.(*Banner))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_UpdateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Banner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).UpdateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.BannerService/UpdateBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).UpdateBanner(ctx, req.(*Banner))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_DeleteBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).DeleteBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.BannerService/DeleteBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).DeleteBanner(ctx, req.(*DeleteBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BannerService_ServiceDesc is the grpc.ServiceDesc for BannerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BannerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.BannerService",
	HandlerType: (*BannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBannerByID",
			Handler:    _BannerService_GetBannerByID_Handler,
		},
		{
			MethodName: "GetBannersByType",
			Handler:    _BannerService_GetBannersByType_Handler,
		},
		{
			MethodName: "ListBanners",
			Handler:    _BannerService_ListBanners_Handler,
		},
		{
			MethodName: "CreateBanner",
			Handler:    _BannerService_CreateBanner_Handler,
		},
		{
			MethodName: "UpdateBanner",
			Handler:    _BannerService_UpdateBanner_Handler,
		},
		{
			MethodName: "DeleteBanner",
			Handler:    _BannerService_DeleteBanner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product/product.proto",
}

// AdsServiceClient is the client API for AdsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdsServiceClient interface {
	GetAdsByLocation(ctx context.Context, in *GetAdsByLocationRequest, opts ...grpc.CallOption) (*GetAdsByLocationResponse, error)
	GetAdsPlacementByID(ctx context.Context, in *GetAdsPlacementByIDRequest, opts ...grpc.CallOption) (*AdsPlacement, error)
	ListAdsPlacements(ctx context.Context, in *ListAdsPlacementsRequest, opts ...grpc.CallOption) (*ListAdsPlacementsResponse, error)
	CreateAdsPlacement(ctx context.Context, in *AdsPlacement, opts ...grpc.CallOption) (*CreateAdsPlacementResponse, error)
	UpdateAdsPlacement(ctx context.Context, in *AdsPlacement, opts ...grpc.CallOption) (*StatusResponse, error)
	DeleteAdsPlacement(ctx context.Context, in *DeleteAdsPlacementRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type adsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdsServiceClient(cc grpc.ClientConnInterface) AdsServiceClient {
	return &adsServiceClient{cc}
}

func (c *adsServiceClient) GetAdsByLocation(ctx context.Context, in *GetAdsByLocationRequest, opts ...grpc.CallOption) (*GetAdsByLocationResponse, error) {
	out := new(GetAdsByLocationResponse)
	err := c.cc.Invoke(ctx, "/product.AdsService/GetAdsByLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) GetAdsPlacementByID(ctx context.Context, in *GetAdsPlacementByIDRequest, opts ...grpc.CallOption) (*AdsPlacement, error) {
	out := new(AdsPlacement)
	err := c.cc.Invoke(ctx, "/product.AdsService/GetAdsPlacementByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) ListAdsPlacements(ctx context.Context, in *ListAdsPlacementsRequest, opts ...grpc.CallOption) (*ListAdsPlacementsResponse, error) {
	out := new(ListAdsPlacementsResponse)
	err := c.cc.Invoke(ctx, "/product.AdsService/ListAdsPlacements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) CreateAdsPlacement(ctx context.Context, in *AdsPlacement, opts ...grpc.CallOption) (*CreateAdsPlacementResponse, error) {
	out := new(CreateAdsPlacementResponse)
	err := c.cc.Invoke(ctx, "/product.AdsService/CreateAdsPlacement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) UpdateAdsPlacement(ctx context.Context, in *AdsPlacement, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.AdsService/UpdateAdsPlacement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) DeleteAdsPlacement(ctx context.Context, in *DeleteAdsPlacementRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/product.AdsService/DeleteAdsPlacement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdsServiceServer is the server API for AdsService service.
// All implementations must embed UnimplementedAdsServiceServer
// for forward compatibility
type AdsServiceServer interface {
	GetAdsByLocation(context.Context, *GetAdsByLocationRequest) (*GetAdsByLocationResponse, error)
	GetAdsPlacementByID(context.Context, *GetAdsPlacementByIDRequest) (*AdsPlacement, error)
	ListAdsPlacements(context.Context, *ListAdsPlacementsRequest) (*ListAdsPlacementsResponse, error)
	CreateAdsPlacement(context.Context, *AdsPlacement) (*CreateAdsPlacementResponse, error)
	UpdateAdsPlacement(context.Context, *AdsPlacement) (*StatusResponse, error)
	DeleteAdsPlacement(context.Context, *DeleteAdsPlacementRequest) (*StatusResponse, error)
	mustEmbedUnimplementedAdsServiceServer()
}

// UnimplementedAdsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdsServiceServer struct {
}

func (UnimplementedAdsServiceServer) GetAdsByLocation(context.Context, *GetAdsByLocationRequest) (*GetAdsByLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdsByLocation not implemented")
}
func (UnimplementedAdsServiceServer) GetAdsPlacementByID(context.Context, *GetAdsPlacementByIDRequest) (*AdsPlacement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdsPlacementByID not implemented")
}
func (UnimplementedAdsServiceServer) ListAdsPlacements(context.Context, *ListAdsPlacementsRequest) (*ListAdsPlacementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdsPlacements not implemented")
}
func (UnimplementedAdsServiceServer) CreateAdsPlacement(context.Context, *AdsPlacement) (*CreateAdsPlacementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAdsPlacement not implemented")
}
func (UnimplementedAdsServiceServer) UpdateAdsPlacement(context.Context, *AdsPlacement) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAdsPlacement not implemented")
}
func (UnimplementedAdsServiceServer) DeleteAdsPlacement(context.Context, *DeleteAdsPlacementRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAdsPlacement not implemented")
}
func (UnimplementedAdsServiceServer) mustEmbedUnimplementedAdsServiceServer() {}

// UnsafeAdsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdsServiceServer will
// result in compilation errors.
type UnsafeAdsServiceServer interface {
	mustEmbedUnimplementedAdsServiceServer()
}

func RegisterAdsServiceServer(s grpc.ServiceRegistrar, srv AdsServiceServer) {
	s.RegisterService(&AdsService_ServiceDesc, srv)
}

func _AdsService_GetAdsByLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdsByLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).GetAdsByLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.AdsService/GetAdsByLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).GetAdsByLocation(ctx, req.(*GetAdsByLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_GetAdsPlacementByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdsPlacementByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).GetAdsPlacementByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.AdsService/GetAdsPlacementByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).GetAdsPlacementByID(ctx, req.(*GetAdsPlacementByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_ListAdsPlacements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdsPlacementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).ListAdsPlacements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.AdsService/ListAdsPlacements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).ListAdsPlacements(ctx, req.(*ListAdsPlacementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_CreateAdsPlacement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdsPlacement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).CreateAdsPlacement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.AdsService/CreateAdsPlacement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).CreateAdsPlacement(ctx, req.(*AdsPlacement))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_UpdateAdsPlacement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdsPlacement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).UpdateAdsPlacement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.AdsService/UpdateAdsPlacement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).UpdateAdsPlacement(ctx, req.(*AdsPlacement))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_DeleteAdsPlacement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdsPlacementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).DeleteAdsPlacement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.AdsService/DeleteAdsPlacement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).DeleteAdsPlacement(ctx, req.(*DeleteAdsPlacementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdsService_ServiceDesc is the grpc.ServiceDesc for AdsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.AdsService",
	HandlerType: (*AdsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdsByLocation",
			Handler:    _AdsService_GetAdsByLocation_Handler,
		},
		{
			MethodName: "GetAdsPlacementByID",
			Handler:    _AdsService_GetAdsPlacementByID_Handler,
		},
		{
			MethodName: "ListAdsPlacements",
			Handler:    _AdsService_ListAdsPlacements_Handler,
		},
		{
			MethodName: "CreateAdsPlacement",
			Handler:    _AdsService_CreateAdsPlacement_Handler,
		},
		{
			MethodName: "UpdateAdsPlacement",
			Handler:    _AdsService_UpdateAdsPlacement_Handler,
		},
		{
			MethodName: "DeleteAdsPlacement",
			Handler:    _AdsService_DeleteAdsPlacement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product/product.proto",
}
