const fs = require("fs");
const urlLimited = "/images/limited/" ;
const urlImgMenCollection = "/images/trending/";
const urlImgTrending = "/images/trending/";
const urlImgTop = "/images/bestselling/";
function escapeString(val) {
  return `'${String(val).replace(/'/g, "''")}'`;
}

function generateProductTagsSQL(products) {
  const sqlLines = [];

  for (const product of products) {
    const productId = escapeString(product.id);
    const tags = product.tags && product.tags.length ? product.tags : ["product"];

    for (const tag of tags) {
      sqlLines.push(`(${productId}, ${escapeString(tag)})`);
    }
  }

  const sql = `INSERT INTO product_tags (product_id, tag) VALUES\n` +
              sqlLines.join(",\n") +
              ";\n";

  fs.writeFileSync("import-product-tags.sql", sql);
  console.log("✅ File import-product-tags.sql đã được tạo thành công!");
}

// ======= Bạn gán mảng `products` ở đây ==========
const products = [
  {
    type: "normal",
    id: "n1",
    name: "2020 Apple MacBook Pro with Apple M1 Chip (13-inch, 8GB RAM, 256GB SSD Storage) - Space Gray",
    slug: "apple-macbook-pro-m1-chip-13-inch-8gb-ram-256gb-ssd-storage-space-gray",
    price: 100.25,
    image_url: "/images/products/grocery/bananas.png",
    originalPrice: 125.99,
    discount: 25,
    description: "The MacBook Air 13-inch is a slim and lightweight laptop from Apple with a sharp Retina display and impressive performance powered by the M1 chip. It's known for its portability, sleek design, and reliable performance.",
    categoryId: "g1",
    categorySlug: "grocery",
    stockQuantity: 5,
    reviews: {
      rating: 4.5,
      count: 10.878,
    },
    orders: 100,
    brand: "Apple",
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/02.png",
      "/images/products/grocery/laptop.png",
      "/images/products/grocery/03.png",
      "/images/products/grocery/04.png",
      "/images/products/grocery/05.png",
      "/images/products/grocery/06.png",
      "/images/products/grocery/bananas.png",

    ],
    tags: ["laptop", "apple", "macbook"],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n2",
    name: "Organic Bananas from sustainable farms",
    slug: "organic-bananas",
    price: 2.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Fresh organic bananas from sustainable farms",
    image_url: "/images/products/grocery/laptop.png",
    categoryId: "g1",
    categorySlug: "grocery",
    stockQuantity: 19,  
    reviews: {
      rating: 4.5,
      count: 10.878,
    },
    brand: "Apple",
    tags: ["apple", "banana", "organic"],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/laptop.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n3",
    name: "Organic Bananas from sustainable farms",
    slug: "organic-bananas1",
    price: 2.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Fresh organic bananas from sustainable farms",
    image_url: "/images/products/grocery/laptop.png",
    categoryId: "g1",
    categorySlug: "grocery",
    stockQuantity: 0,  
    reviews: {
      rating: 4.5,
      count: 10.878,
    },
    orders: 100,
    brand: "Samsung",
    tags: ["samsung", "banana"],
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n4",
    name: "Organic Bananas from sustainable farms",
    slug: "organic-bananas2",
    price: 2.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Fresh organic bananas from sustainable farms",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "g1",
    categorySlug: "grocery",
    stockQuantity: 150,
    reviews: {
      rating: 4.5,
      count: 10.878,
    },
    orders: 100,
    brand: "sony",
    tags: [],
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n5",
    name: "Whole Grain Bread",
    slug: "whole-grain-bread",
    price: 3.49,
    originalPrice: 3.99,
    discount: 25,
    description: "Freshly baked whole grain bread",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "g1",
    categorySlug: "grocery",
    stockQuantity: 75,
    reviews: {
      rating: 4.3,
      count: 10.878,
    },
    orders: 100,
    brand: "sony",
    tags: [],
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n6",
    name: "Free Range Eggs (12pk)",
    slug: "free-range-eggs",
    price: 4.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Farm fresh free-range eggs",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "g1",
    categorySlug: "grocery",
    stockQuantity: 120,
    reviews: {
      rating: 4.7,
      count: 10.878,
    },
    brand: "xiaomi",
    tags: [],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n7",
    name: "Organic Milk",
    slug: "organic-milk",
    price: 3.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Fresh organic whole milk",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "g1",
    categorySlug: "grocery",
    stockQuantity: 95,
    brand: "sony",
    tags: [],
    reviews: {
      rating: 4.2,
      count: 10.878,
    },
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n8",
    name: "Avocados (3pk)",
    slug: "avocados1",
    price: 5.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Ripe and ready to eat avocados",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "g1",
    categorySlug: "grocery",
    stockQuantity: 65,
    reviews: {
      rating: 4.6,
      count: 10.878,
    },
    brand: "sony",
    tags: [],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n9",
    name: "Avocados (3pk)",
    slug: "avocados2",
    price: 5.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Ripe and ready to eat avocados",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "g1",
    categorySlug: "grocery",
    stockQuantity: 65,
    reviews: {
      rating: 4.6,
      count: 10.878,
    },
    orders: 100,
    brand: "sony",
    tags: [],
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },

  // Home Products
  {
    type: "normal",
    id: "n1",
    name: "Scented Candle Set",
    slug: "scented-candle-set",
    price: 24.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Set of 3 aromatic scented candles",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "h2",
    categorySlug: "home",
    stockQuantity: 45,
    orders: 100,
    reviews: {
      rating: 4.4,
      count: 10.878,
    },
    brand: "xiaomi",
    tags: ["xiaomi"],
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n2",
    name: "Cotton Bed Sheets",
    slug: "cotton-bed-sheets",
    price: 49.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Soft 100% Egyptian cotton bed sheets",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "h2",
    categorySlug: "home",
    reviews: {
      rating: 4.7,
      count: 10.878,
    },
    brand: "xiaomi",
    tags: ["xiaomi"],
    stockQuantity: 30,
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n3",
    name: "Kitchen Utensil Set",
    slug: "kitchen-utensil-set1",
    price: 35.99,
    originalPrice: 3.99,
    discount: 25,
    brand: "apple",
    tags: ["apple"],
    description: "Complete set of silicone kitchen utensils",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "h2",
    categorySlug: "home",
    reviews: {
      rating: 4.5,
      count: 10.878,
    },
    stockQuantity: 55,
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n4",
    name: "Decorative Throw Pillows",
    slug: "decorative-throw-pillows1",
    price: 22.99,
    originalPrice: 3.99,
    discount: 25,
    brand: "panasonic",
    tags: ["panasonic"],
    description: "Set of 2 decorative throw pillows for sofa or bed",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "h2",
    categorySlug: "home",
    stockQuantity: 0,
    reviews: {
      rating: 4.3,
      count: 10.878,
    },

    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n5",
    brand: "sony",
    tags: ["sony"],
    name: "LED Table Lamp",
    slug: "led-table-lamp",
    price: 39.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Modern LED table lamp with adjustable brightness",
    image_url: "/images/products/home/lamp.jpg",
    categoryId: "h2",
    categorySlug: "home",
    stockQuantity: 25,
    reviews: {
      rating: 4.3,
      count: 10.878,
    },
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },

  // Fashion Products
  {
    type: "normal",
    id: "n1",
    name: "Women's Denim Jacket",
    slug: "womens-denim-jacket",
    price: 59.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Classic denim jacket for women",
    image_url: "/images/products/fashion/denim-jacket.jpg",
    categoryId: "f3",
    reviews: {
      rating: 4.6,
      count: 10.878,
    },
    brand: "sony",
    tags: ["sony"],
    categorySlug: "fashion",
    stockQuantity: 40,
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n2",
    name: "Men's Casual T-Shirt",
    slug: "mens-casual-tshirt",
    price: 19.99,
    originalPrice: 3.99,
    discount: 25,
    description: "100% cotton casual t-shirt for men",
    image_url: "/images/products/fashion/tshirt.jpg",
    categoryId: "f3",
    categorySlug: "fashion",
    stockQuantity: 120,
    orders: 100,
    brand: "sony",
    tags: ["sony"],
    reviews: {
      rating: 4.3,
      count: 10.878,
    },
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n3",
    name: "Leather Sneakers",
    slug: "leather-sneakers",
    price: 89.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Comfortable leather sneakers for everyday use",
    image_url: "/images/products/fashion/sneakers.jpg",
    categoryId: "f3",
    categorySlug: "fashion",
    stockQuantity: 35,
    orders: 100,
    brand: "sony",
    tags: ["sony"],
    reviews: {
      rating: 4.3,
      count: 10.878,
    },
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n4",
    name: "Summer Dress",
    slug: "summer-dress",
    price: 45.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Lightweight cotton summer dress",
    image_url: "/images/products/fashion/summer-dress.jpg",
    categoryId: "f3",
    categorySlug: "fashion",
    stockQuantity: 0,
    reviews: {
      rating: 4.4,
      count: 10.878,
    },
    brand: "sony",
    tags: ["sony"],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n5",
    name: "Unisex Beanie",
    slug: "unisex-beanie",
    price: 14.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Warm knitted beanie for all seasons",
    image_url: "/images/products/fashion/beanie.jpg",
    categoryId: "f3",
    categorySlug: "fashion",
    stockQuantity: 60,
    orders: 100,
    reviews: {
      rating: 4.2,
      count: 10.878,
    },
    brand: "sony",
    tags: ["sony"],
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },

  // Electronic Products
  {
    type: "normal",
    id: "n1",
    name: "Wireless Earbuds",
    slug: "wireless-earbuds",
    price: 129.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Bluetooth wireless earbuds with noise cancellation",
    image_url: "/images/products/electronics/earbuds.jpg",
    categoryId: "e4",
    categorySlug: "electronic",
    stockQuantity: 45,
    orders: 100,
    reviews: {
      rating: 4.6,
      count: 10.878,
    },
    brand: "sony",
    tags: ["sony"],
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n2",
    name: "4K Smart TV",
    slug: "4k-smart-tv",
    price: 699.99,
    originalPrice: 3.99,
    discount: 25,
    description: "55-inch 4K Ultra HD Smart LED TV",
    image_url: "/images/products/electronics/smart-tv.jpg",
    categoryId: "e4",
    categorySlug: "electronic",
    stockQuantity: 15,
    orders: 100,
    reviews: {
      rating: 4.8,
      count: 10.878,
    },
    brand: "sony",
    tags: ["sony"],
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n3",
    name: "Portable Bluetooth Speaker",
    slug: "portable-bluetooth-speaker",
    price: 89.99,
    originalPrice: 3.99,
    discount: 25,
    description:
      "Waterproof portable bluetooth speaker with 20-hour battery life",
    image_url: "/images/products/electronics/bluetooth-speaker.jpg",
    categoryId: "e4",
    categorySlug: "electronic",
    brand: "sony",
    tags: ["sony"],
    stockQuantity: 30,
    reviews: {
      rating: 4.5,
      count: 10.878,
    },
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n4",
    name: "Digital Camera",
    slug: "digital-camera",
    price: 449.99,
    originalPrice: 3.99,
    discount: 25,
    description: "24MP digital camera with 4K video recording",
    image_url: "/images/products/electronics/digital-camera.jpg",
    categoryId: "e4",
    categorySlug: "electronic",
    stockQuantity: 0,
    brand: "sony",
    tags: ["sony"],
    orders: 100,
    reviews: {
      rating: 4.7,
      count: 10.878,
    },
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
 
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n5",
    name: "Smartwatch",
    slug: "smartwatch",
    price: 199.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Fitness tracking smartwatch with heart rate monitor",
    image_url: "/images/products/electronics/smartwatch.jpg",
    categoryId: "e4",
    categorySlug: "electronic",
    stockQuantity: 25,
    brand: "sony",
    tags: ["sony"],
    reviews: {
      rating: 4.4,
      count: 10.878,
    },
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },

  // Toys Products
  {
    type: "litmited",
    id: "t1",
    name: "Building Blocks Set",
    slug: "building-blocks-set",
    price: 29.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Educational building blocks set for children",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "t5",
    categorySlug: "toys",
    stockQuantity: 50,
    brand: "sony",
    tags: ["sony"],
    reviews: {
      rating: 4.7,
      count: 10.878,
    },
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "trending",
    id: "t2",
    name: "Remote Control Car",
    slug: "remote-control-car",
    price: 49.99,
    originalPrice: 3.99,
    discount: 25,
    description: "High-speed remote control race car",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "t5",
    categorySlug: "toys",
    brand: "piano",
    tags: ["piano"],
    stockQuantity: 35,
    reviews: {
      rating: 4.5,
      count: 10.878,
    },
    orders: 10,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "trending",
    id: "t3",
    name: "Stuffed Teddy Bear",
    slug: "stuffed-teddy-bear",
    price: 19.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Soft and huggable teddy bear for kids",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "t5",
    categorySlug: "toys",
    stockQuantity: 80,
    brand: "piano",
    tags: ["piano"],
    reviews: {
      rating: 4.8,
      count: 10.878,
    },
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "trending",
    id: "t4",
    name: "Educational Board Game",
    slug: "educational-board-game", 
    price: 34.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Family-friendly educational board game",
    image_url: "/images/products/grocery/bananas.png",
    categoryId: "t5",
    categorySlug: "toys",
    stockQuantity: 0,
    orders: 100,
    reviews: {
      rating: 4.6,
      count: 10.878,
    },
    imgSlider: [
      "/images/products/grocery/bananas.png", 
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty", 
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00", 
      global: "3-4 days, $39.00",
    },
    brand: "Educational Games Co.", // Added missing brand property (thương hiệu)
    tags: ["educational", "board game", "family"], // Added missing tags property (thẻ)
  },
  {
    type: "normal",
    id: "n5", 
    name: "Art and Craft Kit",
    slug: "art-and-craft-kit",
    price: 24.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Creative art and craft kit for children",
    image_url: "/images/products/toys/art-kit.jpg",
    categoryId: "t5",
    categorySlug: "toys",
    stockQuantity: 40,
    orders: 100,
      reviews: {
        rating: 4.4,
        count: 10.878,
      },
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
    brand: "piano",
    tags: ["piano"],
  },

  // Additional Grocery Products (for grocery-2)
  {
    type: "trending",
    id: "t6",
    name: "Instant Coffee",
    slug: "instant-coffee",
    price: 7.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Premium instant coffee for quick preparation",
    image_url: "/images/products/grocery/laptop.png",  
    categoryId: "l6",
    categorySlug: "laptop",
    stockQuantity: 70,
    orders: 100,
    reviews: {
      rating: 4.4,
      count: 10.878,
    },
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    brand: "piano",
    tags: ["piano"],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n7",
    name: "Chocolate Cookies",
    slug: "chocolate-cookies",
    price: 3.99,
    originalPrice: 3.99,
    discount: 25,
    description: "Crunchy chocolate chip cookies",
    image_url: "/images/products/grocery/cookies.jpg",
    categoryId: "l6",
    categorySlug: "laptop",
    stockQuantity: 90,
    orders: 100,
    brand: "piano",
    tags: ["piano"],
    reviews: {
      rating: 4.4,
      count: 10.878,
    },
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    type: "normal",
    id: "n8",
    name: "Fresh Orange Juice",
    slug: "fresh-orange-juice",
    price: 4.49,
    originalPrice: 3.99,
    discount: 25,
    description: "100% freshly squeezed orange juice",
    image_url: "/images/products/grocery/orange-juice.jpg",
    categoryId: "l6",
    categorySlug: "laptop",
    stockQuantity: 55,
    reviews: {
      rating: 4.4,
      count: 10.878,
    },
    brand: "sony",
    tags: ["sony"],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: [
      "Free Shipping",
      "Free 1 Year Warranty",
      "100% Money-back guarantee",
      "Secure payment method",
      "24/7 Customer support",
    ],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    id: 't1',
    name: "Radiant Glow Hydrating Serum",
    description:
      "Gentle yet effective, our Radiant Boosting Foaming our Radiant Boosting Foaming our Radiant Boosting Foaming",
    price: 29.99,
    originalPrice: 39.99,
    discount: 20,
    type: "trending",
    reviews: {
      rating: 4.8,
      count: 345,
    },
    image_url: `${urlImgTrending}serum.png`,
    categoryId: "1",
    categorySlug: "grocery",  
    slug: "radiant-glow-hydrating-serum",
    stockQuantity: 5,
    brand: "Brand 1",
    tags: ["tag1", "tag2", "tag3"],
    orders: 100,
    imgSlider: ["image1", "image2", "image3"],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "Courier 1",
      local: "Local 1",
      ups: "UPS 1",
      global: "Global 1",
    },
  },
  {
    type: "trending",
    id: 't2',
    name: "Modern Minimalist Vase",
    description:
      "Track your workouts, heart rate, sleep quality and receive notifications. Water resistant up to 50m with 7-day battery life.",
    price: 40.99,
    originalPrice: 49.99,
    discount: 18,
    reviews: {
      rating: 4.6,
      count: 842,
    },
    image_url: `${urlImgTrending}vase.png`,
    categoryId: "1",
    categorySlug: "grocery",
    slug: "modern-minimalist-vase",
    stockQuantity: 5,
    brand: "Brand 1",
    tags: ["tag1", "tag2", "tag3"],
    orders: 100,
    imgSlider: ["image1", "image2", "image3"],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "Courier 1",
      local: "Local 1",
      ups: "UPS 1",
      global: "Global 1",
    },
  },
  {
    type: "trending",
    id: 't3',
    name: "FitPro 3000 Smart Watch",
    description:
      "Fast-charging power bank with dual USB ports and USB-C compatibility. Charge multiple devices simultaneously on the go.",
    price: 119.99,
    originalPrice: 0,
    discount: 0,
    reviews: {
      rating: 4.0,
      count: 2105,
    },
    image_url: `${urlImgTrending}smartwatch.png`,
    categoryId: "1",
    categorySlug: "grocery",
    slug: "fitpro-3000-smart-watch",
    stockQuantity: 5,
    brand: "Brand 1",
    tags: ["tag1", "tag2", "tag3"],
    orders: 100,
    imgSlider: ["image1", "image2", "image3"],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "Courier 1",
      local: "Local 1",
      ups: "UPS 1",
      global: "Global 1",
    },
  },
  {
    type: "trending",
    id: '1',
    image_url: `${urlImgMenCollection}pants.png`, // Replace with your image path
    price: 25.95,
    discount: 20,
    name: "Pants",
    description: "Pants",
    slug: "pants",
    categoryId: "1",
    categorySlug: "men",
    stockQuantity: 100,
    brand: "Brand 1",
    tags: ["tag1", "tag2", "tag3"],
    reviews: {
      rating: 4.5,
      count: 100,
    },
    originalPrice: 45.95,
    orders: 100,
    imgSlider: ["image1", "image2", "image3"],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "Courier 1",
      local: "Local 1",
      ups: "UPS 1",
      global: "Global 1",
    },
  },
  {
    type: "trending",
    id: '2',
    image_url: `${urlImgMenCollection}shirt.png`, // Replace with your image path
    price: 12.99,
    discount: 0,
    name: "Shirt",
    description: "Shirt",
    slug: "shirt",
    categoryId: "1",
    originalPrice: 12.99,
    categorySlug: "men",
    stockQuantity: 100,
    brand: "Brand 1",
    tags: ["tag1", "tag2", "tag3"],
    reviews: {
      rating: 4.5,
      count: 100,
    },  
    orders: 100,
    imgSlider: ["image1", "image2", "image3"],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "Courier 1",
      local: "Local 1",
      ups: "UPS 1",
      global: "Global 1",
    },
  },
  {
    type: "trending",
    id: '3',
    image_url: `${urlImgMenCollection}hat.png`, // Replace with your image path
    price: 104.0,
    discount: 0,
    originalPrice: 104.0,
    name: "Hat",
    description: "Hat",
    slug: "hat",
    categoryId: "1",
    categorySlug: "men",
    stockQuantity: 100,   
    brand: "Brand 1",
    tags: ["tag1", "tag2", "tag3"],
    reviews: {
      rating: 4.5,
      count: 100,
    },
    orders: 100,
    imgSlider: ["image1", "image2", "image3"],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "Courier 1",
      local: "Local 1",
      ups: "UPS 1",
      global: "Global 1",
    },
  },
  {
    type: "trending",
    id: '4',
    image_url: `${urlImgMenCollection}shoe.png`, // Replace with your image path
    price: 10.56,
    discount: 0,
    originalPrice: 10.56,
    name: "Shoe",
    description: "Shoe",
    slug: "shoe",
    categoryId: "1",
    categorySlug: "men",
    stockQuantity: 100,
    brand: "Brand 1",
    tags: ["tag1", "tag2", "tag3"],
    reviews: {
      rating: 4.5,
      count: 100,
    },
    orders: 100,
    imgSlider: ["image1", "image2", "image3"],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "Courier 1",
      local: "Local 1",
      ups: "UPS 1",
      global: "Global 1",
    },
  },

  {
    type: "limited",
    id: 'l1',
    name: "Samsung Galaxy S24",
    description: "Gentle yet effective, our hydrating serum infuses skin with essential moisture while brightening and plumping for a radiant complexion.",
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    reviews: {
      rating: 4.8,
      count: 345,
    },
    brand: "samsung",
    tags: ["samsung"],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/laptop.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
    image_url: `${urlLimited}samsung_s24.png`,
    slug: "samsung-galaxy-s24",
    categoryId: "l1",
    categorySlug: "limited",
    stockQuantity: 0,
  },
  {
    type: "limited",
    id: 'l2',
    name: "Ui TWS 7002 Earbud",
    description: "Exceptional hydration with antioxidants, hyaluronic acid and collagen for visibly smooth and glowy skin. Fragrance-free for all skin types. [[1]] [[7]]",
    price: 34.99,
    originalPrice: 42.99,
    discount: 18,
    reviews: {
      rating: 4.7,
      count: 287,
    },
    image_url: `${urlLimited}earbud.png`,
    brand: "xiaomi",
    tags: ["xiaomi"],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/laptop.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/bananas.png",
    ],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
    slug: "ui-tws-7002-earbud",
    categoryId: "l1",
    categorySlug: "limited",
    stockQuantity: 0,
  },
  {
    id: 'l3',
    name: "Winter fashion jacket",
    description: "Delivers extreme hydration and helps strengthen the skin barrier. Perfect for both daytime wear and overnight rejuvenation. [[2]]",
    price: 39.99,
    originalPrice: 49.99,
    discount: 20,
    reviews: {
      rating: 4.9,
      count: 412,
    },
    image_url: `${urlLimited}winter_jacket.png`,
    type: "limited",
    slug: "winter-fashion-jacket",
    categoryId: "l1",
    categorySlug: "limited",
    stockQuantity: 0,
    brand: "piano",
    tags: ["piano"],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/laptop.png",
    ],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    id: 'l4',
    name: "New Balance 574 Senekers",
    description: "Illuminating serum infused with glow-boosting intelligent botanicals that leave the skin visibly radiant while reducing redness. [[4]]",
    price: 44.99,
    originalPrice: 59.99,
    discount: 25,
    reviews: {
      rating: 4.6,
      count: 278,
    },
    image_url: `${urlLimited}senekers.png`,
    type: "limited",
    slug: "new-balance-574-senekers",
    categoryId: "l1",
    categorySlug: "limited",
    stockQuantity: 0,
    brand: "new balance",
    tags: ["new balance"],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/laptop.png",
    ],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    id: 'l5',
    name: "Ui TWS 7002 Earbud",
    description: "Exceptional hydration with antioxidants, hyaluronic acid and collagen for visibly smooth and glowy skin. Fragrance-free for all skin types. [[1]] [[7]]",
    price: 34.99,
    originalPrice: 42.99,
    discount: 18,
    reviews: {
      rating: 4.7,
      count: 287,
    },
    image_url: `${urlLimited}earbud.png`,
    type: "limited",
    slug: "ui-tws-7002-earbud",
    categoryId: "l1",
    categorySlug: "limited",
    stockQuantity: 0,
    brand: "xiaomi",
    tags: ["xiaomi"],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/laptop.png",
    ],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    id: 'l6',
    name: "Ui TWS 7002 Earbud",
    description: "Exceptional hydration with antioxidants, hyaluronic acid and collagen for visibly smooth and glowy skin. Fragrance-free for all skin types. [[1]] [[7]]",
    price: 34.99,
    originalPrice: 42.99,
    discount: 18,
    reviews: {
      rating: 4.7,
      count: 287,
    },
    image_url: `${urlLimited}earbud.png`,
    type: "limited",
    slug: "ui-tws-7002-earbud",
    categoryId: "l1",
    categorySlug: "limited",
    stockQuantity: 0,
    brand: "xiaomi",
    tags: ["xiaomi"],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/laptop.png",
    ],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
    id: 'l7',
    name: "Ui TWS 7002 Earbud",
    description: "Exceptional hydration with antioxidants, hyaluronic acid and collagen for visibly smooth and glowy skin. Fragrance-free for all skin types. [[1]] [[7]]",
    price: 34.99,
    originalPrice: 42.99,
    discount: 18,
    reviews: {
      rating: 4.7,
      count: 287,
    },
    image_url: `${urlLimited}earbud.png`,
    type: "limited",
    slug: "ui-tws-7002-earbud",
    categoryId: "l1",
    categorySlug: "limited",
    stockQuantity: 0,
    brand: "xiaomi",
    tags: ["xiaomi"],
    orders: 100,
    imgSlider: [
      "/images/products/grocery/bananas.png",
      "/images/products/grocery/laptop.png",
    ],
    features: ["feature1", "feature2", "feature3"],
    shippingInfo: {
      courier: "2-4 days, free shipping",
      local: "up to one week, $19.00",
      ups: "4-6 days, $29.00",
      global: "3-4 days, $39.00",
    },
  },
  {
      id: 't1', 
      type: "top-sale",
      originalPrice: 12.99,
      discount: 0,
      name: "Computer Accessories",
      uiMetadata: {
        setUpDesign: "row",
        isCommingSoon: true,
      },
      description: "category",
      slug: "computer-accessories",
      price: 12.99,
      categoryId: "t1",
      categorySlug: "top-sell",
      stockQuantity: 0,
      image_url: `${urlImgTop}computer.png`,
      brand: "apple",
      tags: ["apple"],
      reviews: {
        rating: 4.5,
        count: 100,
      },
      orders: 100,
      imgSlider: [
        "/images/products/grocery/bananas.png",
        "/images/products/grocery/laptop.png",
      ],
      features: ["feature1", "feature2", "feature3"],
      shippingInfo: {
        courier: "2-4 days, free shipping",
        local: "up to one week, $19.00",
        ups: "4-6 days, $29.00",
        global: "3-4 days, $39.00",
      },
    },
    {
      id: 't2',
      type: "top-sale", 
      originalPrice: 200,
      discount: 0,
      name: "Men's Casual Outfit",
      price: 200,
      image_url: `${urlImgTop}football.png`,
      uiMetadata: {
        setUpDesign: "row",
        isCommingSoon: false,
      },
      description: "category",
      slug: "men-casual-outfit",
      categoryId: "t1",
      categorySlug: "top-sell",
      stockQuantity: 0,
      brand: "apple",
      tags: ["apple"],
      reviews: {
        rating: 4.5,
        count: 100,
      },
      orders: 100,
      imgSlider: [
        "/images/products/grocery/bananas.png",
        "/images/products/grocery/laptop.png",
      ],
      features: ["feature1", "feature2", "feature3"],
      shippingInfo: {
        courier: "2-4 days, free shipping",
        local: "up to one week, $19.00",
        ups: "4-6 days, $29.00",
        global: "3-4 days, $39.00",
      },
    },
    {
      id: 't3',
      type: "top-sale",
      originalPrice: 49,
      discount: 0,
      name: "Pome Granate Juice",
      price: 49,
      image_url: `${urlImgTop}juice.png`,
      uiMetadata: {
        setUpDesign: "row",
        isCommingSoon: false,
      },
      description: "category",
      slug: "pome-granate-juice",
      categoryId: "t1",
      categorySlug: "top-sell",
      stockQuantity: 0,
      brand: "apple",
      tags: ["apple"],
      reviews: {
        rating: 4.5,
        count: 100,
      },
      orders: 100,
      imgSlider: [
        "/images/products/grocery/bananas.png",
        "/images/products/grocery/laptop.png",
      ],
      features: ["feature1", "feature2", "feature3"],
      shippingInfo: {
        courier: "2-4 days, free shipping",
        local: "up to one week, $19.00",
        ups: "4-6 days, $29.00",
        global: "3-4 days, $39.00",
      },
    },
    {
      id: 't4',
      type: "top-sale",
      name: "Dog Food Made With Love",
      image_url: `${urlImgTop}dog_food.png`,
      uiMetadata: {
        setUpDesign: "col",
        isCommingSoon: false,
      },
      description: "category",
      slug: "dog-food-made-with-love",
      categoryId: "t1",
      categorySlug: "top-sell",
      price: 12.99,
      stockQuantity: 0,
      brand: "apple",
      tags: ["apple"],
      reviews: {
        rating: 4.5,
        count: 100,
      },
      orders: 100,
      originalPrice: 12.99,
      discount: 0,
      imgSlider: [
        "/images/products/grocery/bananas.png",
        "/images/products/grocery/laptop.png",
      ],
      features: ["feature1", "feature2", "feature3"],
      shippingInfo: {
        courier: "2-4 days, free shipping",
        local: "up to one week, $19.00",
        ups: "4-6 days, $29.00",
        global: "3-4 days, $39.00",
      },
    },
    {
      id: 't5',
      type: "top-sale", 
      name: "Security Camera System",
      price: 420,
      originalPrice: 420,
      discount: 0,
      image_url: `${urlImgTop}security_camera.png`,
      uiMetadata: {
        setUpDesign: "double",
        isCommingSoon: false,
      },
      description: "category",
      slug: "security-camera-system",
      categoryId: "t1",
      categorySlug: "top-sell",
      stockQuantity: 0,
      brand: "apple",
      tags: ["apple"],
      reviews: {
        rating: 4.5,
        count: 100,
      },
      orders: 100,
      imgSlider: [
        "/images/products/grocery/bananas.png",
        "/images/products/grocery/laptop.png",
      ],
      features: ["feature1", "feature2", "feature3"],
      shippingInfo: {
        courier: "2-4 days, free shipping",
        local: "up to one week, $19.00",
        ups: "4-6 days, $29.00",
        global: "3-4 days, $39.00",
      },
    },
    {
      id: 't6',
      type: "top-sale",
      name: "Premium Cosmetic Set",
      price: 149,
      originalPrice: 149,
      discount: 0,
      image_url: `${urlImgTop}skincare.png`,
      uiMetadata: {
        setUpDesign: "row",
        isCommingSoon: false,
      },
      description: "category",
      slug: "premium-cosmetic-set",
      categoryId: "t1",
      categorySlug: "top-sell",
      stockQuantity: 0,
      brand: "apple",
      tags: ["apple"],
      reviews: {
        rating: 4.5,
        count: 100,
      },
      orders: 100,
      imgSlider: [
        "/images/products/grocery/bananas.png",
        "/images/products/grocery/laptop.png",
      ],
      features: ["feature1", "feature2", "feature3"],
      shippingInfo: {
        courier: "2-4 days, free shipping",
        local: "up to one week, $19.00",
        ups: "4-6 days, $29.00",
        global: "3-4 days, $39.00",
      },
    }
];

generateProductTagsSQL(products);
