INSERT INTO product_images (id, product_id, url, is_primary, display_order) VALUES
-- Regular products n1-n9 (these IDs exist in the products table)
('n1_0', 'n1', '/images/products/grocery/bananas.png', true, 0),
('n1_1', 'n1', '/images/products/grocery/02.png', false, 1),
('n1_2', 'n1', '/images/products/grocery/laptop.png', false, 2),
('n1_3', 'n1', '/images/products/grocery/03.png', false, 3),
('n1_4', 'n1', '/images/products/grocery/04.png', false, 4),
('n1_5', 'n1', '/images/products/grocery/05.png', false, 5),
('n1_6', 'n1', '/images/products/grocery/06.png', false, 6),
('n1_7', 'n1', '/images/products/grocery/bananas.png', true, 7),
('n2_0', 'n2', '/images/products/grocery/bananas.png', false, 0),
('n2_1', 'n2', '/images/products/grocery/laptop.png', true, 1),
('n2_2', 'n2', '/images/products/grocery/bananas.png', false, 2),
('n2_3', 'n2', '/images/products/grocery/bananas.png', false, 3),
('n2_4', 'n2', '/images/products/grocery/bananas.png', false, 4),
('n3_0', 'n3', '/images/products/grocery/bananas.png', false, 0),
('n3_1', 'n3', '/images/products/grocery/bananas.png', false, 1),
('n3_2', 'n3', '/images/products/grocery/bananas.png', false, 2),
('n3_3', 'n3', '/images/products/grocery/bananas.png', false, 3),
('n3_4', 'n3', '/images/products/grocery/bananas.png', false, 4),
('n3_5', 'n3', '/images/products/grocery/laptop.png', true, 5),
('n4_0', 'n4', '/images/products/grocery/bananas.png', true, 0),
('n4_1', 'n4', '/images/products/grocery/bananas.png', true, 1),
('n4_2', 'n4', '/images/products/grocery/bananas.png', true, 2),
('n4_3', 'n4', '/images/products/grocery/bananas.png', true, 3),
('n4_4', 'n4', '/images/products/grocery/bananas.png', true, 4),
('n5_0', 'n5', '/images/products/grocery/bananas.png', true, 0),
('n5_1', 'n5', '/images/products/grocery/bananas.png', true, 1),
('n5_2', 'n5', '/images/products/grocery/bananas.png', true, 2),
('n5_3', 'n5', '/images/products/grocery/bananas.png', true, 3),
('n5_4', 'n5', '/images/products/grocery/bananas.png', true, 4),
('n6_0', 'n6', '/images/products/grocery/bananas.png', true, 0),
('n6_1', 'n6', '/images/products/grocery/bananas.png', true, 1),
('n6_2', 'n6', '/images/products/grocery/bananas.png', true, 2),
('n6_3', 'n6', '/images/products/grocery/bananas.png', true, 3),
('n6_4', 'n6', '/images/products/grocery/bananas.png', true, 4),
('n7_0', 'n7', '/images/products/grocery/bananas.png', true, 0),
('n7_1', 'n7', '/images/products/grocery/bananas.png', true, 1),
('n7_2', 'n7', '/images/products/grocery/bananas.png', true, 2),
('n7_3', 'n7', '/images/products/grocery/bananas.png', true, 3),
('n7_4', 'n7', '/images/products/grocery/bananas.png', true, 4),
('n8_0', 'n8', '/images/products/grocery/bananas.png', true, 0),
('n8_1', 'n8', '/images/products/grocery/bananas.png', true, 1),
('n8_2', 'n8', '/images/products/grocery/bananas.png', true, 2),
('n8_3', 'n8', '/images/products/grocery/bananas.png', true, 3),
('n8_4', 'n8', '/images/products/grocery/bananas.png', true, 4),
('n9_0', 'n9', '/images/products/grocery/bananas.png', true, 0),
('n9_1', 'n9', '/images/products/grocery/bananas.png', true, 1),
('n9_2', 'n9', '/images/products/grocery/bananas.png', true, 2),
('n9_3', 'n9', '/images/products/grocery/bananas.png', true, 3),
('n9_4', 'n9', '/images/products/grocery/bananas.png', true, 4),

-- Products n10-n28 
('n10_0', 'n10', '/images/products/grocery/bananas.png', true, 0),
('n12_0', 'n12', '/images/products/grocery/bananas.png', true, 1),
('n13_0', 'n13', '/images/products/grocery/bananas.png', true, 2),
('n14_0', 'n14', '/images/products/grocery/bananas.png', true, 3),
('n15_0', 'n15', '/images/products/grocery/bananas.png', true, 4),

-- Product images for n16-n25
('n16_0', 'n16', '/images/products/grocery/bananas.png', true, 0),
('n17_0', 'n17', '/images/products/grocery/bananas.png', true, 1),
('n18_0', 'n18', '/images/products/grocery/bananas.png', true, 2),
('n19_0', 'n19', '/images/products/grocery/bananas.png', true, 3),
('n20_0', 'n20', '/images/products/grocery/bananas.png', true, 4),
('n21_0', 'n21', '/images/products/grocery/bananas.png', true, 0),
('n22_0', 'n22', '/images/products/grocery/bananas.png', true, 1),
('n23_0', 'n23', '/images/products/grocery/bananas.png', true, 2),
('n24_0', 'n24', '/images/products/grocery/bananas.png', true, 3),
('n25_0', 'n25', '/images/products/grocery/bananas.png', true, 4),

-- Products n26-n28
('n26_0', 'n26', '/images/products/grocery/bananas.png', false, 0),
('n27_0', 'n27', '/images/products/grocery/bananas.png', false, 1),
('n28_0', 'n28', '/images/products/grocery/bananas.png', false, 2),

-- Home category products with specialized images
('n15_1', 'n15', '/images/products/home/lamp.jpg', true, 5),

-- Fashion category products with specialized images
('n16_1', 'n16', '/images/products/fashion/denim-jacket.jpg', true, 5),
('n17_1', 'n17', '/images/products/fashion/tshirt.jpg', true, 5),
('n18_1', 'n18', '/images/products/fashion/sneakers.jpg', true, 5),
('n19_1', 'n19', '/images/products/fashion/summer-dress.jpg', true, 5),
('n20_1', 'n20', '/images/products/fashion/beanie.jpg', true, 5),

-- Electronic category products with specialized images
('n21_1', 'n21', '/images/products/electronics/earbuds.jpg', true, 5),
('n22_1', 'n22', '/images/products/electronics/smart-tv.jpg', true, 5),
('n23_1', 'n23', '/images/products/electronics/bluetooth-speaker.jpg', true, 5),
('n24_1', 'n24', '/images/products/electronics/digital-camera.jpg', true, 5),
('n25_1', 'n25', '/images/products/electronics/smartwatch.jpg', true, 5),

-- Trending products (t1-t4, t6)
('t1_0', 't1', '/images/products/grocery/bananas.png', true, 0),
('t1_1', 't1', '/images/products/grocery/bananas.png', true, 1),
('t1_2', 't1', '/images/products/grocery/bananas.png', true, 2),
('t1_3', 't1', '/images/products/grocery/bananas.png', true, 3),
('t1_4', 't1', '/images/products/grocery/bananas.png', true, 4),
('t2_0', 't2', '/images/products/grocery/bananas.png', true, 0),
('t2_1', 't2', '/images/products/grocery/bananas.png', true, 1),
('t2_2', 't2', '/images/products/grocery/bananas.png', true, 2),
('t2_3', 't2', '/images/products/grocery/bananas.png', true, 3),
('t2_4', 't2', '/images/products/grocery/bananas.png', true, 4),
('t3_0', 't3', '/images/products/grocery/bananas.png', true, 0),
('t3_1', 't3', '/images/products/grocery/bananas.png', true, 1),
('t3_2', 't3', '/images/products/grocery/bananas.png', true, 2),
('t3_3', 't3', '/images/products/grocery/bananas.png', true, 3),
('t3_4', 't3', '/images/products/grocery/bananas.png', true, 4),
('t4_0', 't4', '/images/products/grocery/bananas.png', true, 0),
('t4_1', 't4', '/images/products/grocery/bananas.png', true, 1),
('t4_2', 't4', '/images/products/grocery/bananas.png', true, 2),
('t4_3', 't4', '/images/products/grocery/bananas.png', true, 3),
('t4_4', 't4', '/images/products/grocery/bananas.png', true, 4),

-- n28 (toys)
('n28_1', 'n28', '/images/products/toys/art-kit.jpg', true, 5),

-- t6 (trending)
('t6_0', 't6', '/images/products/grocery/bananas.png', false, 0),
('t6_1', 't6', '/images/products/grocery/bananas.png', false, 1),
('t6_2', 't6', '/images/products/grocery/bananas.png', false, 2),
('t6_3', 't6', '/images/products/grocery/bananas.png', false, 3),
('t6_4', 't6', '/images/products/grocery/bananas.png', false, 4),
('t6_5', 't6', '/images/products/grocery/laptop.png', true, 5),

-- n26, n27 (laptop products)
('n26_1', 'n26', '/images/products/grocery/cookies.jpg', true, 5),
('n27_1', 'n27', '/images/products/grocery/orange-juice.jpg', true, 5),

-- Trending products with specialized images (t7-t14)
('t7_0', 't7', 'image1', false, 0),
('t7_1', 't7', 'image2', false, 1),
('t7_2', 't7', 'image3', false, 2),
('t7_3', 't7', '/images/trending/serum.png', true, 3),
('t8_0', 't8', 'image1', false, 0),
('t8_1', 't8', 'image2', false, 1),
('t8_2', 't8', 'image3', false, 2),
('t8_3', 't8', '/images/trending/vase.png', true, 3),
('t9_0', 't9', 'image1', false, 0),
('t9_1', 't9', 'image2', false, 1),
('t9_2', 't9', 'image3', false, 2),
('t9_3', 't9', '/images/trending/smartwatch.png', true, 3),
('t10_0', 't10', 'image1', false, 0),
('t10_1', 't10', 'image2', false, 1),
('t10_2', 't10', 'image3', false, 2),
('t10_3', 't10', '/images/trending/pants.png', true, 3),
('t11_0', 't11', 'image1', false, 0),
('t11_1', 't11', 'image2', false, 1),
('t11_2', 't11', 'image3', false, 2),
('t11_3', 't11', '/images/trending/shirt.png', true, 3),
('t13_0', 't13', 'image1', false, 0),
('t13_1', 't13', 'image2', false, 1),
('t13_2', 't13', 'image3', false, 2),
('t13_3', 't13', '/images/trending/hat.png', true, 3),
('t14_0', 't14', 'image1', false, 0),
('t14_1', 't14', 'image2', false, 1),
('t14_2', 't14', 'image3', false, 2),
('t14_3', 't14', '/images/trending/shoe.png', true, 3),

-- Limited edition products (l1-l7)
('l1_0', 'l1', '/images/products/grocery/bananas.png', false, 0),
('l1_1', 'l1', '/images/products/grocery/laptop.png', false, 1),
('l1_2', 'l1', '/images/products/grocery/bananas.png', false, 2),
('l1_3', 'l1', '/images/products/grocery/bananas.png', false, 3),
('l1_4', 'l1', '/images/products/grocery/bananas.png', false, 4),
('l1_5', 'l1', '/images/limited/samsung_s24.png', true, 5),
('l2_0', 'l2', '/images/products/grocery/bananas.png', false, 0),
('l2_1', 'l2', '/images/products/grocery/laptop.png', false, 1),
('l2_2', 'l2', '/images/products/grocery/bananas.png', false, 2),
('l2_3', 'l2', '/images/products/grocery/bananas.png', false, 3),
('l2_4', 'l2', '/images/products/grocery/bananas.png', false, 4),
('l2_5', 'l2', '/images/limited/earbud.png', true, 5),
('l3_0', 'l3', '/images/products/grocery/bananas.png', false, 0),
('l3_1', 'l3', '/images/products/grocery/laptop.png', false, 1),
('l3_2', 'l3', '/images/limited/winter_jacket.png', true, 2),
('l4_0', 'l4', '/images/products/grocery/bananas.png', false, 0),
('l4_1', 'l4', '/images/products/grocery/laptop.png', false, 1),
('l4_2', 'l4', '/images/limited/senekers.png', true, 2),
('l5_0', 'l5', '/images/products/grocery/bananas.png', false, 0),
('l5_1', 'l5', '/images/products/grocery/laptop.png', false, 1),
('l5_2', 'l5', '/images/limited/earbud.png', true, 2),
('l6_0', 'l6', '/images/products/grocery/bananas.png', false, 0),
('l6_1', 'l6', '/images/products/grocery/laptop.png', false, 1),
('l6_2', 'l6', '/images/limited/earbud.png', true, 2),
('l7_0', 'l7', '/images/products/grocery/bananas.png', false, 0),
('l7_1', 'l7', '/images/products/grocery/laptop.png', false, 1),
('l7_2', 'l7', '/images/limited/earbud.png', true, 2),

-- Top sale products (top1-top6)
('top1_0', 'top1', '/images/products/grocery/bananas.png', false, 0),
('top1_1', 'top1', '/images/products/grocery/laptop.png', false, 1),
('top1_2', 'top1', '/images/bestselling/computer.png', true, 2),
('top2_0', 'top2', '/images/products/grocery/bananas.png', false, 0),
('top2_1', 'top2', '/images/products/grocery/laptop.png', false, 1),
('top2_2', 'top2', '/images/bestselling/football.png', true, 2),
('top3_0', 'top3', '/images/products/grocery/bananas.png', false, 0),
('top3_1', 'top3', '/images/products/grocery/laptop.png', false, 1),
('top3_2', 'top3', '/images/bestselling/juice.png', true, 2),
('top4_0', 'top4', '/images/products/grocery/bananas.png', false, 0),
('top4_1', 'top4', '/images/products/grocery/laptop.png', false, 1),
('top4_2', 'top4', '/images/bestselling/dog_food.png', true, 2),
('top5_0', 'top5', '/images/products/grocery/bananas.png', false, 0),
('top5_1', 'top5', '/images/products/grocery/laptop.png', false, 1),
('top5_2', 'top5', '/images/bestselling/security_camera.png', true, 2),
('top6_0', 'top6', '/images/products/grocery/bananas.png', false, 0),
('top6_1', 'top6', '/images/products/grocery/laptop.png', false, 1),
('top6_2', 'top6', '/images/bestselling/skincare.png', true, 2);
