INSERT INTO product_tags (product_id, tag) VALUES
-- Regular products n1-n9 with appropriate tags
('n1', 'laptop'),
('n1', 'apple'),
('n1', 'macbook'),
('n2', 'banana'),
('n2', 'organic'),
('n2', 'apple'),
('n3', 'samsung'),
('n3', 'banana'),
('n4', 'product'),
('n4', 'sony'),
('n5', 'product'),
('n5', 'sony'),
('n6', 'product'),
('n6', 'xiaomi'),
('n7', 'product'),
('n7', 'sony'),
('n8', 'product'),
('n8', 'sony'),
('n9', 'product'),
('n9', 'sony'),

-- Products n10-n28 with brand tags
('n10', 'home'),
('n12', 'home'),
('n13', 'home'),
('n14', 'home'),
('n15', 'home'),
('n16', 'fashion'),
('n17', 'fashion'),
('n18', 'fashion'),
('n19', 'fashion'),
('n20', 'fashion'),
('n21', 'electronics'),
('n22', 'electronics'),
('n23', 'electronics'),
('n24', 'electronics'),
('n25', 'electronics'),
('n26', 'grocery'),
('n27', 'grocery'),
('n28', 'toys'),

-- Trending products (t1-t6)
('t1', 'toy'),
('t1', 'building'),
('t1', 'educational'),
('t2', 'toy'),
('t2', 'remote'),
('t2', 'piano'),
('t3', 'toy'),
('t3', 'teddy'),
('t3', 'piano'),
('t4', 'educational'),
('t4', 'board game'),
('t4', 'family'),
('t6', 'coffee'),
('t6', 'instant'),
('t6', 'piano'),

-- More trending products (t7-t14)
('t7', 'beauty'),
('t7', 'serum'),
('t7', 'skincare'),
('t8', 'home'),
('t8', 'vase'),
('t8', 'decoration'),
('t9', 'electronics'),
('t9', 'smartwatch'),
('t9', 'fitness'),
('t10', 'fashion'),
('t10', 'pants'),
('t10', 'clothing'),
('t11', 'fashion'),
('t11', 'shirt'),
('t11', 'clothing'),
('t13', 'fashion'),
('t13', 'hat'),
('t13', 'accessory'),
('t14', 'fashion'),
('t14', 'shoe'),
('t14', 'footwear'),

-- Limited edition products (l1-l7)
('l1', 'samsung'),
('l1', 'smartphone'),
('l1', 'electronics'),
('l2', 'xiaomi'),
('l2', 'earbuds'),
('l2', 'audio'),
('l3', 'piano'),
('l3', 'jacket'),
('l3', 'winter'),
('l4', 'new balance'),
('l4', 'sneakers'),
('l4', 'footwear'),
('l5', 'xiaomi'),
('l5', 'earbuds'),
('l5', 'audio'),
('l6', 'xiaomi'),
('l6', 'electronics'),
('l7', 'xiaomi'),
('l7', 'electronics'),

-- Top sale products (top1-top6)
('top1', 'computer'),
('top1', 'accessories'),
('top1', 'apple'),
('top2', 'outfit'),
('top2', 'men'),
('top2', 'casual'),
('top3', 'juice'),
('top3', 'drink'),
('top3', 'healthy'),
('top4', 'pet'),
('top4', 'dog'),
('top4', 'food'),
('top5', 'security'),
('top5', 'camera'),
('top5', 'electronics'),
('top6', 'cosmetic'),
('top6', 'beauty'),
('top6', 'skincare');
