// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: proto/payment/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	// Create payment for MoMo gateway
	CreateMomoPayment(ctx context.Context, in *MomoPaymentRequest, opts ...grpc.CallOption) (*MomoPaymentResponse, error)
	// Verify MoMo payment callback
	VerifyMomoPayment(ctx context.Context, in *MomoVerifyRequest, opts ...grpc.CallOption) (*PaymentVerifyResponse, error)
	// Process MoMo payment callback from broker service
	ProcessMomoCallback(ctx context.Context, in *MomoCallbackRequest, opts ...grpc.CallOption) (*PaymentVerifyResponse, error)
	// Create payment for VNPAY gateway
	CreateVnpayPayment(ctx context.Context, in *VnpayPaymentRequest, opts ...grpc.CallOption) (*VnpayPaymentResponse, error)
	// Verify VNPAY payment callback
	VerifyVnpayPayment(ctx context.Context, in *VnpayVerifyRequest, opts ...grpc.CallOption) (*PaymentVerifyResponse, error)
	// MoMo QuickPay methods
	CreateMomoQRPayment(ctx context.Context, in *MomoQRPaymentRequest, opts ...grpc.CallOption) (*MomoQuickPayResponse, error)
	CreateMomoPosPayment(ctx context.Context, in *MomoPosPaymentRequest, opts ...grpc.CallOption) (*MomoQuickPayResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreateMomoPayment(ctx context.Context, in *MomoPaymentRequest, opts ...grpc.CallOption) (*MomoPaymentResponse, error) {
	out := new(MomoPaymentResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/CreateMomoPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) VerifyMomoPayment(ctx context.Context, in *MomoVerifyRequest, opts ...grpc.CallOption) (*PaymentVerifyResponse, error) {
	out := new(PaymentVerifyResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/VerifyMomoPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ProcessMomoCallback(ctx context.Context, in *MomoCallbackRequest, opts ...grpc.CallOption) (*PaymentVerifyResponse, error) {
	out := new(PaymentVerifyResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/ProcessMomoCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreateVnpayPayment(ctx context.Context, in *VnpayPaymentRequest, opts ...grpc.CallOption) (*VnpayPaymentResponse, error) {
	out := new(VnpayPaymentResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/CreateVnpayPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) VerifyVnpayPayment(ctx context.Context, in *VnpayVerifyRequest, opts ...grpc.CallOption) (*PaymentVerifyResponse, error) {
	out := new(PaymentVerifyResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/VerifyVnpayPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreateMomoQRPayment(ctx context.Context, in *MomoQRPaymentRequest, opts ...grpc.CallOption) (*MomoQuickPayResponse, error) {
	out := new(MomoQuickPayResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/CreateMomoQRPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreateMomoPosPayment(ctx context.Context, in *MomoPosPaymentRequest, opts ...grpc.CallOption) (*MomoQuickPayResponse, error) {
	out := new(MomoQuickPayResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/CreateMomoPosPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility
type PaymentServiceServer interface {
	// Create payment for MoMo gateway
	CreateMomoPayment(context.Context, *MomoPaymentRequest) (*MomoPaymentResponse, error)
	// Verify MoMo payment callback
	VerifyMomoPayment(context.Context, *MomoVerifyRequest) (*PaymentVerifyResponse, error)
	// Process MoMo payment callback from broker service
	ProcessMomoCallback(context.Context, *MomoCallbackRequest) (*PaymentVerifyResponse, error)
	// Create payment for VNPAY gateway
	CreateVnpayPayment(context.Context, *VnpayPaymentRequest) (*VnpayPaymentResponse, error)
	// Verify VNPAY payment callback
	VerifyVnpayPayment(context.Context, *VnpayVerifyRequest) (*PaymentVerifyResponse, error)
	// MoMo QuickPay methods
	CreateMomoQRPayment(context.Context, *MomoQRPaymentRequest) (*MomoQuickPayResponse, error)
	CreateMomoPosPayment(context.Context, *MomoPosPaymentRequest) (*MomoQuickPayResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (UnimplementedPaymentServiceServer) CreateMomoPayment(context.Context, *MomoPaymentRequest) (*MomoPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMomoPayment not implemented")
}
func (UnimplementedPaymentServiceServer) VerifyMomoPayment(context.Context, *MomoVerifyRequest) (*PaymentVerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyMomoPayment not implemented")
}
func (UnimplementedPaymentServiceServer) ProcessMomoCallback(context.Context, *MomoCallbackRequest) (*PaymentVerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMomoCallback not implemented")
}
func (UnimplementedPaymentServiceServer) CreateVnpayPayment(context.Context, *VnpayPaymentRequest) (*VnpayPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVnpayPayment not implemented")
}
func (UnimplementedPaymentServiceServer) VerifyVnpayPayment(context.Context, *VnpayVerifyRequest) (*PaymentVerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyVnpayPayment not implemented")
}
func (UnimplementedPaymentServiceServer) CreateMomoQRPayment(context.Context, *MomoQRPaymentRequest) (*MomoQuickPayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMomoQRPayment not implemented")
}
func (UnimplementedPaymentServiceServer) CreateMomoPosPayment(context.Context, *MomoPosPaymentRequest) (*MomoQuickPayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMomoPosPayment not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreateMomoPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MomoPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateMomoPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/CreateMomoPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateMomoPayment(ctx, req.(*MomoPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_VerifyMomoPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MomoVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).VerifyMomoPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/VerifyMomoPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).VerifyMomoPayment(ctx, req.(*MomoVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ProcessMomoCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MomoCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ProcessMomoCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/ProcessMomoCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ProcessMomoCallback(ctx, req.(*MomoCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CreateVnpayPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VnpayPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateVnpayPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/CreateVnpayPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateVnpayPayment(ctx, req.(*VnpayPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_VerifyVnpayPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VnpayVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).VerifyVnpayPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/VerifyVnpayPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).VerifyVnpayPayment(ctx, req.(*VnpayVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CreateMomoQRPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MomoQRPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateMomoQRPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/CreateMomoQRPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateMomoQRPayment(ctx, req.(*MomoQRPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CreateMomoPosPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MomoPosPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateMomoPosPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/CreateMomoPosPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateMomoPosPayment(ctx, req.(*MomoPosPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMomoPayment",
			Handler:    _PaymentService_CreateMomoPayment_Handler,
		},
		{
			MethodName: "VerifyMomoPayment",
			Handler:    _PaymentService_VerifyMomoPayment_Handler,
		},
		{
			MethodName: "ProcessMomoCallback",
			Handler:    _PaymentService_ProcessMomoCallback_Handler,
		},
		{
			MethodName: "CreateVnpayPayment",
			Handler:    _PaymentService_CreateVnpayPayment_Handler,
		},
		{
			MethodName: "VerifyVnpayPayment",
			Handler:    _PaymentService_VerifyVnpayPayment_Handler,
		},
		{
			MethodName: "CreateMomoQRPayment",
			Handler:    _PaymentService_CreateMomoQRPayment_Handler,
		},
		{
			MethodName: "CreateMomoPosPayment",
			Handler:    _PaymentService_CreateMomoPosPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/payment/payment.proto",
}
