apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-cart-secret
  namespace: ecommerce
type: Opaque
stringData:
  REDIS_HOST: "redis-cart"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  REDIS_DB: "0"
  AUTO_REDIS_INIT: "false" 