apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: ecommerce
  labels:
    app: redis-cart
spec:
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    app: redis-cart 